### ISSUE TITLE
New-CaasServerDetails not working with Customer Templates

### ISSUE THREAD

**Issue by lduplessis** [DimensionDataCBUSydney/Compute.Api.Powershell#27]
Wonder if someone can point me in the right direction.

I trying to create a VM form a customer template using powershell. If using the following command:

$serverDetails = New-CaasServerDetails -Name $machineName -AdminPassword $adminPass -IsStarted $powerState -NetworkDomain $networkdomain -PrimaryVlan $vlan -PrimaryDns $primarydns -SecondaryDns $secondarydns -ServerImage $serverImage -CpuSpeed $vcputype -CpuCount $vcpu -MemoryGb $vram -CpuCoresPerSocket 1 

I get the following message:

New-CaasServerDetails : ServerImage type cannot be converted to DD.CBU.Compute.Api.Contracts.Image.ImagesWithDiskSpeedImageor 
toDD.CBU.Compute.Api.Contracts.Network20.OsImageType
At C:\support store\Server Builder\VMBuilder.ps1:231 char:26
+         $serverDetails = New-CaasServerDetails -Name $machineName -AdminPassword ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-CaasServerDetails], ArgumentException
    + FullyQualifiedErrorId : -3,DD.CBU.Compute.Powershell.NewCaasServerDetailsCmdlet 

Can I use powershell to create a Virtual machine from a customer template?
What does ImagesWithDiskSpeedImage mean?

**Comment by tintoy** [comment]
Hi - what version of the module are you using?

**Comment by tintoy** [comment]
Could you try installing the [latest release] ( https://github.com/DimensionDataCBUSydney/Compute.Api.Powershell/releases/tag/v3.4.0) and trying again?

**Comment by lduplessis** [comment]
I have installed the latest release and the issue is resolved, thank you

**Comment by tintoy** [comment]
Thanks, @lduplessis, and sorry for the inconvenience!
